### ISSUE TITLE
Quick Link Share

### ISSUE THREAD

**Issue by knotbin** [knotbin/memento#11]
**Is your feature request related to a problem? Please describe.**
Sharing links involves an extra tap even when you wouldn't like to add a note.

**Describe the solution you'd like**
When you press Memento in the share sheet, a "saved" screen appears for about a second and disappears unless you tap to edit it.

**Additional context**
See GoodLinks' implementation [here](https://imgur.com/a/k6qdWi4) as the goal/example of good implementation of this feature.

**Comment by Bentheminernz** [comment]
You can mark this as closed as its added in v1.1.0
